sample_list = []
print(f'The sample list before appending: {sample_list}')
print(f'The id of sample list before appending: {id(sample_list)}')
sample_list.append('Ramesh')
sample_list.append('Gauri')
sample_list.append('Pooja')
sample_list.append('Bhuwan')
sample_list.append('Surya')
print(f'The final sample list after appending names: {sample_list}')
print(f'The id of sample list after appending: {id(sample_list)}')
print('No! the id of list is not changed.')
sample_list.sort()
print(f'The sample list after sorting: {sample_list}')
print(f'The first item in the list is: {sample_list[0]}')
print(f'The second item in the list is: {sample_list[1]}')